#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QLSX_2.Resource", IsApplication=true)]

namespace QLSX_2
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040002
			public const int activity_horizontal_margin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_vertical_margin = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int nav_header_height = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int nav_header_vertical_spacing = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cell_shape = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int delete = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gradient_bg = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int gradient_bg_alternate = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int gradient_bg_hover = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int gradient_bg_hover_alternate = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int image_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int input_shape = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int list_selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int list_selector_alternate = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int BCTP_listView = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int BCXuatTP_listView = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int CPK_btnAdd = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int ChiPhiKhac_btnSearch = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int ChiPhiKhac_listView = 2131165207;
			
			// aapt resource value: 0x7f070015
			public const int ChiPhiKhac_txtSearch = 2131165205;
			
			// aapt resource value: 0x7f0700b2
			public const int DGNhapTP_edit = 2131165362;
			
			// aapt resource value: 0x7f0700e2
			public const int DGXuatNLDaSCCP_edit_text = 2131165410;
			
			// aapt resource value: 0x7f0700cb
			public const int DGXuatNLSoche_edit_text = 2131165387;
			
			// aapt resource value: 0x7f0700dc
			public const int DGXuatTP_edit_text = 2131165404;
			
			// aapt resource value: 0x7f070096
			public const int DVTCPK_edit_text = 2131165334;
			
			// aapt resource value: 0x7f0700a5
			public const int DVTNLDaSC_edit_text = 2131165349;
			
			// aapt resource value: 0x7f0700aa
			public const int DiachiNV_edit_text = 2131165354;
			
			// aapt resource value: 0x7f070003
			public const int Diachi_edit = 2131165187;
			
			// aapt resource value: 0x7f0700e7
			public const int DonvitinhSP_edit_text = 2131165415;
			
			// aapt resource value: 0x7f0700ac
			public const int EmailNV_edit_text = 2131165356;
			
			// aapt resource value: 0x7f070005
			public const int Email_edit = 2131165189;
			
			// aapt resource value: 0x7f07009f
			public const int GiaCPK_edit_text = 2131165343;
			
			// aapt resource value: 0x7f0700a9
			public const int HoTenNV_edit_text = 2131165353;
			
			// aapt resource value: 0x7f070002
			public const int HoTen_edit = 2131165186;
			
			// aapt resource value: 0x7f0700a1
			public const int HuyCPKCT = 2131165345;
			
			// aapt resource value: 0x7f0700ae
			public const int HuyNV = 2131165358;
			
			// aapt resource value: 0x7f0700cd
			public const int HuyPXNLDaSCCT = 2131165389;
			
			// aapt resource value: 0x7f0700de
			public const int HuyPXTPCT = 2131165406;
			
			// aapt resource value: 0x7f0700e9
			public const int HuySP = 2131165417;
			
			// aapt resource value: 0x7f070019
			public const int KH_btnAdd = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int KH_btnSearch = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int KH_listView = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int KH_txtSearch = 2131165210;
			
			// aapt resource value: 0x7f0700a0
			public const int LuuCPKCT = 2131165344;
			
			// aapt resource value: 0x7f0700cc
			public const int LuuPXNLDaSCCT = 2131165388;
			
			// aapt resource value: 0x7f0700dd
			public const int LuuPXTPCT = 2131165405;
			
			// aapt resource value: 0x7f0700e8
			public const int LuuSP = 2131165416;
			
			// aapt resource value: 0x7f070094
			public const int MaChiPhiKhac_edit_text = 2131165332;
			
			// aapt resource value: 0x7f070001
			public const int MaKH_edit = 2131165185;
			
			// aapt resource value: 0x7f0700a3
			public const int MaNLDaSC_edit_text = 2131165347;
			
			// aapt resource value: 0x7f0700a8
			public const int MaNV_edit_text = 2131165352;
			
			// aapt resource value: 0x7f0700b9
			public const int MaPhieuThu_edit = 2131165369;
			
			// aapt resource value: 0x7f0700c0
			public const int MaPhieuXuatNLDaSC_edit_text = 2131165376;
			
			// aapt resource value: 0x7f0700cf
			public const int MaPhieuXuatTP_edit_text = 2131165391;
			
			// aapt resource value: 0x7f0700e5
			public const int MaSP_edit_text = 2131165413;
			
			// aapt resource value: 0x7f070073
			public const int NLDaSC_btnAdd = 2131165299;
			
			// aapt resource value: 0x7f070075
			public const int NLDaSC_btnSearch = 2131165301;
			
			// aapt resource value: 0x7f070076
			public const int NLDaSC_listView = 2131165302;
			
			// aapt resource value: 0x7f070074
			public const int NLDaSC_txtSearch = 2131165300;
			
			// aapt resource value: 0x7f070077
			public const int NhanVien_btnAdd = 2131165303;
			
			// aapt resource value: 0x7f070079
			public const int NhanVien_btnSearch = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int NhanVien_listView = 2131165306;
			
			// aapt resource value: 0x7f070078
			public const int NhanVien_txtSearch = 2131165304;
			
			// aapt resource value: 0x7f07007b
			public const int PNTPCT_btnAdd = 2131165307;
			
			// aapt resource value: 0x7f07007d
			public const int PNTPCT_btnSearch = 2131165309;
			
			// aapt resource value: 0x7f07007e
			public const int PNTPCT_listView = 2131165310;
			
			// aapt resource value: 0x7f07007c
			public const int PNTPCT_txtSearch = 2131165308;
			
			// aapt resource value: 0x7f0700b8
			public const int PT_spKH = 2131165368;
			
			// aapt resource value: 0x7f0700b6
			public const int PT_spNV = 2131165366;
			
			// aapt resource value: 0x7f070083
			public const int PXNLDaSCCP_btnAdd = 2131165315;
			
			// aapt resource value: 0x7f070085
			public const int PXNLDaSCCP_btnSearch = 2131165317;
			
			// aapt resource value: 0x7f070086
			public const int PXNLDaSCCP_listView = 2131165318;
			
			// aapt resource value: 0x7f070084
			public const int PXNLDaSCCP_txtSearch = 2131165316;
			
			// aapt resource value: 0x7f0700e0
			public const int PXNLDaSCCoCP_spCPK = 2131165408;
			
			// aapt resource value: 0x7f0700df
			public const int PXNLDaSCCoCP_spPhieuXNLDaSC = 2131165407;
			
			// aapt resource value: 0x7f070087
			public const int PXNLDaSC_btnAdd = 2131165319;
			
			// aapt resource value: 0x7f070089
			public const int PXNLDaSC_btnSearch = 2131165321;
			
			// aapt resource value: 0x7f07008a
			public const int PXNLDaSC_listView = 2131165322;
			
			// aapt resource value: 0x7f0700c2
			public const int PXNLDaSC_spNV = 2131165378;
			
			// aapt resource value: 0x7f070088
			public const int PXNLDaSC_txtSearch = 2131165320;
			
			// aapt resource value: 0x7f07008b
			public const int PXTP_btnAdd = 2131165323;
			
			// aapt resource value: 0x7f07008d
			public const int PXTP_btnSearch = 2131165325;
			
			// aapt resource value: 0x7f07008e
			public const int PXTP_listView = 2131165326;
			
			// aapt resource value: 0x7f0700d3
			public const int PXTP_spKH = 2131165395;
			
			// aapt resource value: 0x7f0700d1
			public const int PXTP_spNV = 2131165393;
			
			// aapt resource value: 0x7f07008c
			public const int PXTP_txtSearch = 2131165324;
			
			// aapt resource value: 0x7f07007f
			public const int PhieuThu_btnAdd = 2131165311;
			
			// aapt resource value: 0x7f070081
			public const int PhieuThu_btnSearch = 2131165313;
			
			// aapt resource value: 0x7f070082
			public const int PhieuThu_listView = 2131165314;
			
			// aapt resource value: 0x7f070080
			public const int Phieuthu_txtSearch = 2131165312;
			
			// aapt resource value: 0x7f0700b1
			public const int SLNhapTP_edit = 2131165361;
			
			// aapt resource value: 0x7f0700e1
			public const int SLXuatNLDaSCCP_edit_text = 2131165409;
			
			// aapt resource value: 0x7f0700ca
			public const int SLXuatNLSoche_edit_text = 2131165386;
			
			// aapt resource value: 0x7f0700db
			public const int SLXuatTP_edit_text = 2131165403;
			
			// aapt resource value: 0x7f0700ab
			public const int SoDTNV_edit_text = 2131165355;
			
			// aapt resource value: 0x7f070004
			public const int SoDT_edit = 2131165188;
			
			// aapt resource value: 0x7f0700bc
			public const int SoTienthu_edit = 2131165372;
			
			// aapt resource value: 0x7f07008f
			public const int TP_btnAdd = 2131165327;
			
			// aapt resource value: 0x7f070091
			public const int TP_btnSearch = 2131165329;
			
			// aapt resource value: 0x7f070092
			public const int TP_listView = 2131165330;
			
			// aapt resource value: 0x7f070090
			public const int TP_txtSearch = 2131165328;
			
			// aapt resource value: 0x7f070095
			public const int TenCPK_edit_text = 2131165333;
			
			// aapt resource value: 0x7f0700a4
			public const int TenNLDaSC_edit_text = 2131165348;
			
			// aapt resource value: 0x7f0700e6
			public const int TenSP_edit_text = 2131165414;
			
			// aapt resource value: 0x7f0700ad
			public const int ThemNV = 2131165357;
			
			// aapt resource value: 0x7f0700c4
			public const int btnChon_PXNLDaSC = 2131165380;
			
			// aapt resource value: 0x7f0700d5
			public const int btnChon_PhieuxuatTP = 2131165397;
			
			// aapt resource value: 0x7f070007
			public const int btnHuy = 2131165191;
			
			// aapt resource value: 0x7f07009a
			public const int btnHuyChiPhiKhac = 2131165338;
			
			// aapt resource value: 0x7f0700a7
			public const int btnHuyNLDaSC = 2131165351;
			
			// aapt resource value: 0x7f0700be
			public const int btnHuyPT = 2131165374;
			
			// aapt resource value: 0x7f0700b4
			public const int btnHuyPhieuNhapTP = 2131165364;
			
			// aapt resource value: 0x7f0700e4
			public const int btnHuyPhieuXNLDaSCCP = 2131165412;
			
			// aapt resource value: 0x7f0700c8
			public const int btnHuyPhieuxuatNLDaSC = 2131165384;
			
			// aapt resource value: 0x7f0700d9
			public const int btnHuyPhieuxuatTP = 2131165401;
			
			// aapt resource value: 0x7f07000d
			public const int btnLoad_BC = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int btnLoad_BCXuatTP = 2131165202;
			
			// aapt resource value: 0x7f070006
			public const int btnLuu = 2131165190;
			
			// aapt resource value: 0x7f070099
			public const int btnLuuChiPhiKhac = 2131165337;
			
			// aapt resource value: 0x7f0700a6
			public const int btnLuuNLDaSC = 2131165350;
			
			// aapt resource value: 0x7f0700bd
			public const int btnLuuPT = 2131165373;
			
			// aapt resource value: 0x7f0700b3
			public const int btnLuuPhieuNhapTP = 2131165363;
			
			// aapt resource value: 0x7f0700e3
			public const int btnLuuPhieuXNLDaSCCP = 2131165411;
			
			// aapt resource value: 0x7f0700c7
			public const int btnLuuPhieuxuatNLDaSC = 2131165383;
			
			// aapt resource value: 0x7f0700d8
			public const int btnLuuPhieuxuatTP = 2131165400;
			
			// aapt resource value: 0x7f0700c6
			public const int btnThemDSNguyenLieuDaSC = 2131165382;
			
			// aapt resource value: 0x7f0700d7
			public const int btnThemDSThanhPham = 2131165399;
			
			// aapt resource value: 0x7f070098
			public const int btnThemNgayCPK = 2131165336;
			
			// aapt resource value: 0x7f07009e
			public const int btnThemNgay_ChiPhiKhac = 2131165342;
			
			// aapt resource value: 0x7f070072
			public const int btn_reg_create = 2131165298;
			
			// aapt resource value: 0x7f070064
			public const int btnlogin = 2131165284;
			
			// aapt resource value: 0x7f070065
			public const int btnregister = 2131165285;
			
			// aapt resource value: 0x7f07006f
			public const int button_BC = 2131165295;
			
			// aapt resource value: 0x7f07001e
			public const int button_BCNhapTP = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int button_BCXuatTP = 2131165215;
			
			// aapt resource value: 0x7f07006c
			public const int button_CPK = 2131165292;
			
			// aapt resource value: 0x7f07006e
			public const int button_GT = 2131165294;
			
			// aapt resource value: 0x7f070069
			public const int button_KH = 2131165289;
			
			// aapt resource value: 0x7f07006a
			public const int button_NL = 2131165290;
			
			// aapt resource value: 0x7f070021
			public const int button_NPXNLDaSCCP = 2131165217;
			
			// aapt resource value: 0x7f070068
			public const int button_NV = 2131165288;
			
			// aapt resource value: 0x7f070066
			public const int button_PNhap = 2131165286;
			
			// aapt resource value: 0x7f070020
			public const int button_PXNLDaSC = 2131165216;
			
			// aapt resource value: 0x7f070022
			public const int button_PXTP = 2131165218;
			
			// aapt resource value: 0x7f070067
			public const int button_PXuat = 2131165287;
			
			// aapt resource value: 0x7f07006d
			public const int button_Pthu = 2131165293;
			
			// aapt resource value: 0x7f07006b
			public const int button_TP = 2131165291;
			
			// aapt resource value: 0x7f0700c3
			public const int date_PXNLDaSC = 2131165379;
			
			// aapt resource value: 0x7f0700d4
			public const int date_PhieuxuatTP = 2131165396;
			
			// aapt resource value: 0x7f0700ba
			public const int date_display = 2131165370;
			
			// aapt resource value: 0x7f0700bb
			public const int date_select_button = 2131165371;
			
			// aapt resource value: 0x7f07003d
			public const int lr_BtndeleteNV = 2131165245;
			
			// aapt resource value: 0x7f070041
			public const int lr_DGNhapTP = 2131165249;
			
			// aapt resource value: 0x7f070052
			public const int lr_DGXuatNLDaSC = 2131165266;
			
			// aapt resource value: 0x7f07004d
			public const int lr_DGXuatNLDaSCCoCP = 2131165261;
			
			// aapt resource value: 0x7f070030
			public const int lr_DVTChiPhiKhac = 2131165232;
			
			// aapt resource value: 0x7f070037
			public const int lr_DVTNLDaSC = 2131165239;
			
			// aapt resource value: 0x7f07005f
			public const int lr_DVTTP = 2131165279;
			
			// aapt resource value: 0x7f07002c
			public const int lr_DiaChi = 2131165228;
			
			// aapt resource value: 0x7f07003c
			public const int lr_DiaChiNV = 2131165244;
			
			// aapt resource value: 0x7f07005b
			public const int lr_DonGiaPXTPCT = 2131165275;
			
			// aapt resource value: 0x7f070033
			public const int lr_GiaChiPhiKhac = 2131165235;
			
			// aapt resource value: 0x7f07004b
			public const int lr_MaCPK_PXNLDaSCCP = 2131165259;
			
			// aapt resource value: 0x7f07002e
			public const int lr_MaChiPhiKhac = 2131165230;
			
			// aapt resource value: 0x7f070056
			public const int lr_MaKH_PXTP = 2131165270;
			
			// aapt resource value: 0x7f070035
			public const int lr_MaNLDaSC = 2131165237;
			
			// aapt resource value: 0x7f07004f
			public const int lr_MaNLDaSC_PXNLDaSCCT = 2131165263;
			
			// aapt resource value: 0x7f070048
			public const int lr_MaNV_PXNLDaSC = 2131165256;
			
			// aapt resource value: 0x7f070043
			public const int lr_MaPhieu = 2131165251;
			
			// aapt resource value: 0x7f070054
			public const int lr_MaPhieuXTP = 2131165268;
			
			// aapt resource value: 0x7f070047
			public const int lr_MaPhieuXuatNLDaSC = 2131165255;
			
			// aapt resource value: 0x7f07003e
			public const int lr_MaPhieuXuatNLDaSC_PNTPCT = 2131165246;
			
			// aapt resource value: 0x7f07005d
			public const int lr_MaTP = 2131165277;
			
			// aapt resource value: 0x7f07003f
			public const int lr_MaTP_PNTPCT = 2131165247;
			
			// aapt resource value: 0x7f070058
			public const int lr_MaTP_PXTPCT = 2131165272;
			
			// aapt resource value: 0x7f070044
			public const int lr_Ngay = 2131165252;
			
			// aapt resource value: 0x7f070032
			public const int lr_NgayChiPhiKhac = 2131165234;
			
			// aapt resource value: 0x7f070024
			public const int lr_NgayNhapBC = 2131165220;
			
			// aapt resource value: 0x7f070055
			public const int lr_NgayPhieuXuatTP = 2131165269;
			
			// aapt resource value: 0x7f070027
			public const int lr_NgayXuatBC = 2131165223;
			
			// aapt resource value: 0x7f070049
			public const int lr_NgayXuatNLDaSC = 2131165257;
			
			// aapt resource value: 0x7f070023
			public const int lr_PhieuNhapBC = 2131165219;
			
			// aapt resource value: 0x7f070026
			public const int lr_PhieuXuatBC = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int lr_SLNhapBC = 2131165221;
			
			// aapt resource value: 0x7f070040
			public const int lr_SLNhapTP = 2131165248;
			
			// aapt resource value: 0x7f07005a
			public const int lr_SLPXTPCT = 2131165274;
			
			// aapt resource value: 0x7f070028
			public const int lr_SLXuatBC = 2131165224;
			
			// aapt resource value: 0x7f070051
			public const int lr_SLXuatNLDaSC = 2131165265;
			
			// aapt resource value: 0x7f07004c
			public const int lr_SLXuatNLDaSCCoCP = 2131165260;
			
			// aapt resource value: 0x7f07002a
			public const int lr_SoDT = 2131165226;
			
			// aapt resource value: 0x7f07003a
			public const int lr_SoDTNV = 2131165242;
			
			// aapt resource value: 0x7f070045
			public const int lr_Sotien = 2131165253;
			
			// aapt resource value: 0x7f07002f
			public const int lr_TenChiPhiKhac = 2131165231;
			
			// aapt resource value: 0x7f070036
			public const int lr_TenNLDaSC = 2131165238;
			
			// aapt resource value: 0x7f070050
			public const int lr_TenNLDaSC_PXNLDaSCCT = 2131165264;
			
			// aapt resource value: 0x7f070039
			public const int lr_TenNV = 2131165241;
			
			// aapt resource value: 0x7f07005e
			public const int lr_TenTP = 2131165278;
			
			// aapt resource value: 0x7f070059
			public const int lr_TenTP_PXTPCT = 2131165273;
			
			// aapt resource value: 0x7f070038
			public const int lr_btnDelete_NLDaSC = 2131165240;
			
			// aapt resource value: 0x7f070042
			public const int lr_btnDelete_PNTPCT = 2131165250;
			
			// aapt resource value: 0x7f07004a
			public const int lr_btnDelete_PXNLDaSC = 2131165258;
			
			// aapt resource value: 0x7f07004e
			public const int lr_btnDelete_PXNLDaSCCoCP = 2131165262;
			
			// aapt resource value: 0x7f070057
			public const int lr_btnDelete_PXTP = 2131165271;
			
			// aapt resource value: 0x7f07005c
			public const int lr_btnDelete_PXTPCT = 2131165276;
			
			// aapt resource value: 0x7f070034
			public const int lr_btndelete_CPKCT = 2131165236;
			
			// aapt resource value: 0x7f070031
			public const int lr_btndelete_ChiPhiKhac = 2131165233;
			
			// aapt resource value: 0x7f07002d
			public const int lr_deleteBtn = 2131165229;
			
			// aapt resource value: 0x7f070046
			public const int lr_deleteBtnPT = 2131165254;
			
			// aapt resource value: 0x7f070060
			public const int lr_deleteBtnTP = 2131165280;
			
			// aapt resource value: 0x7f070053
			public const int lr_deleteBtn_PXNLDaSCCT = 2131165267;
			
			// aapt resource value: 0x7f07002b
			public const int lr_email = 2131165227;
			
			// aapt resource value: 0x7f07003b
			public const int lr_emailNV = 2131165243;
			
			// aapt resource value: 0x7f070029
			public const int lr_fullName = 2131165225;
			
			// aapt resource value: 0x7f070097
			public const int lsNgayGia = 2131165335;
			
			// aapt resource value: 0x7f0700c5
			public const int lsPhieuXuatNLDaSCChitiet = 2131165381;
			
			// aapt resource value: 0x7f0700d6
			public const int lvPhieuxuatTPChitiet = 2131165398;
			
			// aapt resource value: 0x7f0700c9
			public const int spMaNLDaSC_PXNLDaSCCT = 2131165385;
			
			// aapt resource value: 0x7f07009c
			public const int spMaNgay_CPKCT = 2131165340;
			
			// aapt resource value: 0x7f0700af
			public const int spMaPhieuXuatNLDaSC = 2131165359;
			
			// aapt resource value: 0x7f0700b0
			public const int spMaTP_PNTP = 2131165360;
			
			// aapt resource value: 0x7f0700da
			public const int spMaTP_PXTPCT = 2131165402;
			
			// aapt resource value: 0x7f07000a
			public const int sp_TPBC = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int sp_TPBCXTP = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int tableLayout = 2131165192;
			
			// aapt resource value: 0x7f07009b
			public const int text = 2131165339;
			
			// aapt resource value: 0x7f07001d
			public const int text1 = 2131165213;
			
			// aapt resource value: 0x7f070093
			public const int textCPK = 2131165331;
			
			// aapt resource value: 0x7f0700a2
			public const int textNL = 2131165346;
			
			// aapt resource value: 0x7f0700ce
			public const int textPXTP = 2131165390;
			
			// aapt resource value: 0x7f070061
			public const int textView1 = 2131165281;
			
			// aapt resource value: 0x7f0700bf
			public const int textd = 2131165375;
			
			// aapt resource value: 0x7f070009
			public const int textview = 2131165193;
			
			// aapt resource value: 0x7f0700b7
			public const int tvMaKH_PT = 2131165367;
			
			// aapt resource value: 0x7f0700d2
			public const int tvMaKH_PXTP = 2131165394;
			
			// aapt resource value: 0x7f0700b5
			public const int tvMaNV_PT = 2131165365;
			
			// aapt resource value: 0x7f0700c1
			public const int tvMaNV_PXNL = 2131165377;
			
			// aapt resource value: 0x7f0700d0
			public const int tvMaNV_PXTP = 2131165392;
			
			// aapt resource value: 0x7f070018
			public const int tv_Gioithieu = 2131165208;
			
			// aapt resource value: 0x7f07009d
			public const int txtNgayCPK = 2131165341;
			
			// aapt resource value: 0x7f070011
			public const int txtSLTonTP = 2131165201;
			
			// aapt resource value: 0x7f07000c
			public const int txtSoLuongTP = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int txtTongNhapTP = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int txtTongXuatTP = 2131165200;
			
			// aapt resource value: 0x7f070071
			public const int txt_reg_password = 2131165297;
			
			// aapt resource value: 0x7f070070
			public const int txt_reg_username = 2131165296;
			
			// aapt resource value: 0x7f070000
			public const int txt_title = 2131165184;
			
			// aapt resource value: 0x7f070063
			public const int txtpwd = 2131165283;
			
			// aapt resource value: 0x7f070062
			public const int txtusername = 2131165282;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddEditKhachHang = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BaoCaoTP = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BaoCaoXuatTP = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ChiPhiKhac = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Gioithieu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int KhachHang = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int layoutBaoCao = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int layoutPhieuXuat = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int list_row_BCTPNhap = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int list_row_BCTPXuat = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int list_row_contact_list = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int list_row_CPK = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int list_row_CPKChiTiet = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int list_row_NLDaSC = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int list_row_NV = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int list_row_PNTPCT = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int list_row_PT = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int list_row_PXNLDaSC = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int list_row_PXNLDaSCCoCP = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int list_row_PXNLDaSCCT = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int list_row_PXTP = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int list_row_PXTPCT = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int list_row_TP = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Login = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Main = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Newuser = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int NguyenLieuDaSoChe = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int NhanVien = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int PhieuNhapTPChiTiet = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int PhieuThu = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int PhieuXuatNLDaSCCP = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int PhieuXuatNLDaSoChe = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int PhieuXuatTP = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int ThanhPham = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int ThemChiPhiKhac = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int ThemChiPhiKhacChiTiet = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int ThemNguyenLieuDaSC = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int ThemNhanVien = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int ThemPhieuNhapTPchitiet = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int ThemPhieuThu = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int ThemPhieuXNLDaSoChe = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int ThemPhieuXuatNLDaSCChiTiet = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int ThemPhieuXuatTP = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int ThemPhieuXuatTPChiTiet = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int ThemPXNLDaSCCoCP = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int ThemThanhPham = 2130903085;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int DataName = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int button_style = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int input_style = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
